GET http://localhost:3000/api/users/ HTTP/1.1

###

POST http://localhost:3000/api/users/register HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZmNiZDk3MjRlYjIwNzdlNDE0YTlkZiIsInVzZXJuYW1lIjoiMTk4Mzg5Iiwicm9sZSI6WyJhZG1pbiJdLCJpYXQiOjE3MzYwNDc1NjIsImV4cCI6MTczNjA3NjM2Mn0.SBF70ZoaSEmMRgyi0Q_aXc-CqY8tXSVx__05JljFEaM

{
  "username": "1983s8s9s",
  "password":"password",
  "firstName":"password",
  "roles": ["student"]
}

###

POST https://clg-super-app.onrender.com/api/auth/login HTTP/1.1
content-type: application/json

{
  "username": "admin",
  "password": "password"
}

###

GET https://clg-super-app.onrender.com/api/employees HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3N2UzYjFlNDVkODEzNTZmOTA3ZDRhMyIsInVzZXJuYW1lIjoiYWRtaW4iLCJyb2xlIjpbInN1cGVyIl0sImlhdCI6MTczOTMyOTYyNCwiZXhwIjoxNzM5MzU4NDI0fQ.Kj5-RqQrNAtVuCGAuxTN2BSnkbTwgSzHEvf04S7I4Kk

{
  
}
###
# Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZmNiZDk3MjRlYjIwNzdlNDE0YTlkZiIsInVzZXJuYW1lIjoiMTk4Mzg5IiwiaWF0IjoxNzI3ODQzMjg4LCJleHAiOjE3Mjc4NzIwODh9.gabd72P5mNt4aMCyOWVGNqccfdtpN4HpOm7953C3Nq0

