GET http://localhost:3000/api/users/ HTTP/1.1

###

POST http://localhost:3000/api/users/register HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZmNiZDk3MjRlYjIwNzdlNDE0YTlkZiIsInVzZXJuYW1lIjoiMTk4Mzg5Iiwicm9sZSI6WyJhZG1pbiJdLCJpYXQiOjE3MzYwNDc1NjIsImV4cCI6MTczNjA3NjM2Mn0.SBF70ZoaSEmMRgyi0Q_aXc-CqY8tXSVx__05JljFEaM

{
  "username": "1983s8s9s",
  "password":"password",
  "firstName":"password",
  "roles": ["student"]
}

###

POST http://localhost:3000/api/auth/login HTTP/1.1
content-type: application/json

{
  "username": "admin",
  "password": "password"
}

###

POST http://localhost:3000/api/employees/add HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZmNiZDk3MjRlYjIwNzdlNDE0YTlkZiIsInVzZXJuYW1lIjoiMTk4Mzg5Iiwicm9sZSI6WyJhZG1pbiJdLCJpYXQiOjE3MzYxMzU2NTksImV4cCI6MTczNjE2NDQ1OX0.K23qOk6GcNr0cbGe9SNI3FfXafZ77d7SEYfT92vUUq4

###
# Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZmNiZDk3MjRlYjIwNzdlNDE0YTlkZiIsInVzZXJuYW1lIjoiMTk4Mzg5IiwiaWF0IjoxNzI3ODQzMjg4LCJleHAiOjE3Mjc4NzIwODh9.gabd72P5mNt4aMCyOWVGNqccfdtpN4HpOm7953C3Nq0


GET http://localhost:3000/api/schedules HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3N2UzYjFlNDVkODEzNTZmOTA3ZDRhMyIsInVzZXJuYW1lIjoiYWRtaW4iLCJyb2xlIjpbInN1cGVyIl0sImlhdCI6MTc0MTIyNjk1OCwiZXhwIjoxNzQxMjU1NzU4fQ.PZ4HtpKXIkLAIbGtd-X5Bb7gPTVsICUN23jN3A6jw_k


###

POST http://localhost:3000/api/schedules HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3N2UzYjFlNDVkODEzNTZmOTA3ZDRhMyIsInVzZXJuYW1lIjoiYWRtaW4iLCJyb2xlIjpbInN1cGVyIl0sImlhdCI6MTc0MTIyNjk1OCwiZXhwIjoxNzQxMjU1NzU4fQ.PZ4HtpKXIkLAIbGtd-X5Bb7gPTVsICUN23jN3A6jw_k

