GET http://localhost:3000/api/users/ HTTP/1.1

###

POST http://localhost:3000/api/users/register HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZmNiZDk3MjRlYjIwNzdlNDE0YTlkZiIsInVzZXJuYW1lIjoiMTk4Mzg5Iiwicm9sZSI6WyJ1c2VyIl0sImlhdCI6MTcyNzg0NjkyMywiZXhwIjoxNzI3ODc1NzIzfQ.1xb99Z0PKuhPiafCkV38M4aLyK-OngKjBi72sAVPZ-A

{
  "username": "1983s8s9",
  "password": "sadsadasd",
  "roles": ["admin"]
}

###

POST http://localhost:3000/api/users/login HTTP/1.1
content-type: application/json

{
  "username": "198389",
  "password": "sadsadasd"
}


###
# Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZmNiZDk3MjRlYjIwNzdlNDE0YTlkZiIsInVzZXJuYW1lIjoiMTk4Mzg5IiwiaWF0IjoxNzI3ODQzMjg4LCJleHAiOjE3Mjc4NzIwODh9.gabd72P5mNt4aMCyOWVGNqccfdtpN4HpOm7953C3Nq0

